name: user-check
on: [push]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check by linter and user tests
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: sudo apt-get install -y make
      - run: python3 -m pip install poetry
      - run: make build
      - run: make install
      - run: make lint
